name: Update Another Blacklist

on:
  push:
    paths:
      - 'whitelist.txt'
      - 'config.json'
  schedule:
    - cron: "30 03 * * *"
  workflow_dispatch:

jobs:
  generate_and_commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: "Setup sing-box"
      env:
        SING_BOX_DEB_URL: "https://github.com/SagerNet/sing-box/releases/download/v1.12.0-beta.13/sing-box_1.12.0-beta.13_linux_amd64.deb"
      run: |
          set -Eeuo pipefail
          wget -O sing-box.deb $SING_BOX_DEB_URL
          sudo dpkg -i sing-box.deb

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Downloads From Upstream
      run: |
        python scripts/01_update_blacklist.py
        python scripts/02_parsing.py
        python scripts/03_merge.py
        python scripts/04_convert.py

    - name: Move files to release branch
      run: |
        mkdir -p release/domains release/json release/plain release/srs
        mv domains/* release/domains/
        mv json/* release/json/
        mv plain/* release/plain/
        mv srs/* release/srs/

    - name: Push changes to release branch
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: release
        directory: release
        force: true
